/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import eg.edu.alexu.csd.oop.game.GameEngine;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author Arwa Mohamed
 */
public class Main extends javax.swing.JFrame {
     private Image backgroundImage;
    
    public Main() {
    initComponents();
    setSize(750, 800);  // Set the window size
    setLocationRelativeTo(null);  // Center the window
}

    @Override
    public void paint(Graphics g) {
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
        super.paint(g);
    }
      
    /**
     * Creates new form Main
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moderateButton = new javax.swing.JButton();
        hardButton = new javax.swing.JButton();
        easyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        moderateButton.setBackground(new java.awt.Color(255, 204, 51));
        moderateButton.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        moderateButton.setForeground(new java.awt.Color(153, 0, 0));
        moderateButton.setText("Moderate");
        moderateButton.setBorderPainted(false);
        moderateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moderateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(moderateButton);
        moderateButton.setBounds(240, 600, 250, 50);

        hardButton.setBackground(new java.awt.Color(255, 204, 51));
        hardButton.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        hardButton.setForeground(new java.awt.Color(153, 0, 0));
        hardButton.setText("Hard");
        hardButton.setBorderPainted(false);
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hardButton);
        hardButton.setBounds(500, 600, 210, 50);

        easyButton.setBackground(new java.awt.Color(255, 204, 51));
        easyButton.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        easyButton.setForeground(new java.awt.Color(153, 0, 0));
        easyButton.setText("Easy");
        easyButton.setBorderPainted(false);
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(easyButton);
        easyButton.setBounds(20, 600, 210, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w.jpg"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -150, 1000, 1060);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moderateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moderateButtonActionPerformed
        // TODO add your handling code here:
        
        ModerateLevel ml=new ModerateLevel();
        JMenuBar menuTab = new JMenuBar() ;
        JMenu menu = new JMenu(  "Game Settings");
        JMenuItem newGame = new JMenuItem(  "New Game");
        JMenuItem pause= new JMenuItem( "Pause Game") ;
        JMenuItem resume = new JMenuItem(  "Resume");
        menu.add ( newGame);
        menu.addSeparator();
        menu.add ( pause);
        menu.add ( resume);
        menuTab.add(menu);
         final GameEngine.GameController gc = GameEngine.start("Circus World",new CircusWorld(1250,750,ml ));
//       JFrame gameFrame = (JFrame) menuTab.getParent().getParent().getParent();
        JFrame gameFrame = new Circus();
        gameFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        gameFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (JOptionPane.showConfirmDialog(gameFrame, "Are you sure you want to close this game?",
                        "End Game?", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                    gameFrame.dispose();
                    Main newFrame = new Main();
                    newFrame.setVisible(true);
                    //some code to return to game main window.
                }
            }
        });
         newGame.addActionListener((ActionEvent e) -> {
            gc.changeWorld(new CircusWorld(1250,750,ml));
        });
        pause.addActionListener((ActionEvent e) -> {
            gc.pause();
        });
        resume.addActionListener((ActionEvent e) -> {
            gc.resume();
        });
        this.setVisible(false);
    }//GEN-LAST:event_moderateButtonActionPerformed

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        // TODO add your handling code here:
        HardLevel hl=new HardLevel();
        GameEngine.start("Circus World",new CircusWorld(1250,750,hl));
      
    }//GEN-LAST:event_hardButtonActionPerformed

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        // TODO add your handling code here:
        EasyLevel el=new EasyLevel();
        final GameEngine.GameController gc=GameEngine.start("Circus World",new CircusWorld(1250,750,el));
    
    }//GEN-LAST:event_easyButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         Main frame = new Main();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new JFrameWithImageBackground());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }


    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton moderateButton;
    // End of variables declaration//GEN-END:variables
}
